version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgres://exp_dev:replace_me_dev@postgres:5432/evenly_dev
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=evenly_dev
      - POSTGRES_USER=exp_dev
      - POSTGRES_PASSWORD=replace_me_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exp_dev -d evenly_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: